package com.example.demo.generator.mapper;

import com.example.demo.generator.domain.City;
import java.util.List;

public interface CityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_city
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer ctid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_city
     *
     * @mbggenerated
     */
    int insert(City record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_city
     *
     * @mbggenerated
     */
    City selectByPrimaryKey(Integer ctid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_city
     *
     * @mbggenerated
     */
    List<City> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_city
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(City record);
}