package com.example.demo.generator.domain;

import java.io.Serializable;
import java.util.Date;

public class City implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_city.CTID
     *
     * @mbggenerated
     */
    private Integer ctid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_city.CODE
     *
     * @mbggenerated
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_city.CTCODE
     *
     * @mbggenerated
     */
    private Integer ctcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_city.CTVALUE
     *
     * @mbggenerated
     */
    private String ctvalue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_city.CTORDER
     *
     * @mbggenerated
     */
    private Integer ctorder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_city.CTHASCHILD
     *
     * @mbggenerated
     */
    private Integer cthaschild;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_city.CTCOMMENT
     *
     * @mbggenerated
     */
    private String ctcomment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_city.CTVALUE1
     *
     * @mbggenerated
     */
    private String ctvalue1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_city.CTVALUE2
     *
     * @mbggenerated
     */
    private String ctvalue2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_city.CTVALUE3
     *
     * @mbggenerated
     */
    private String ctvalue3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_city.CTVALUE4
     *
     * @mbggenerated
     */
    private String ctvalue4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_city.CTPARENT
     *
     * @mbggenerated
     */
    private Integer ctparent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_city.DELETED
     *
     * @mbggenerated
     */
    private Byte deleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_city.CREATED_BY
     *
     * @mbggenerated
     */
    private Integer createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_city.CREATED_TIME
     *
     * @mbggenerated
     */
    private Date createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_city.UPDATED_BY
     *
     * @mbggenerated
     */
    private Integer updatedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_city.UPDATED_TIME
     *
     * @mbggenerated
     */
    private Date updatedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_city.VERSION
     *
     * @mbggenerated
     */
    private Short version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_city
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_city.CTID
     *
     * @return the value of sys_city.CTID
     *
     * @mbggenerated
     */
    public Integer getCtid() {
        return ctid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_city.CTID
     *
     * @param ctid the value for sys_city.CTID
     *
     * @mbggenerated
     */
    public void setCtid(Integer ctid) {
        this.ctid = ctid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_city.CODE
     *
     * @return the value of sys_city.CODE
     *
     * @mbggenerated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_city.CODE
     *
     * @param code the value for sys_city.CODE
     *
     * @mbggenerated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_city.CTCODE
     *
     * @return the value of sys_city.CTCODE
     *
     * @mbggenerated
     */
    public Integer getCtcode() {
        return ctcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_city.CTCODE
     *
     * @param ctcode the value for sys_city.CTCODE
     *
     * @mbggenerated
     */
    public void setCtcode(Integer ctcode) {
        this.ctcode = ctcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_city.CTVALUE
     *
     * @return the value of sys_city.CTVALUE
     *
     * @mbggenerated
     */
    public String getCtvalue() {
        return ctvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_city.CTVALUE
     *
     * @param ctvalue the value for sys_city.CTVALUE
     *
     * @mbggenerated
     */
    public void setCtvalue(String ctvalue) {
        this.ctvalue = ctvalue == null ? null : ctvalue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_city.CTORDER
     *
     * @return the value of sys_city.CTORDER
     *
     * @mbggenerated
     */
    public Integer getCtorder() {
        return ctorder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_city.CTORDER
     *
     * @param ctorder the value for sys_city.CTORDER
     *
     * @mbggenerated
     */
    public void setCtorder(Integer ctorder) {
        this.ctorder = ctorder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_city.CTHASCHILD
     *
     * @return the value of sys_city.CTHASCHILD
     *
     * @mbggenerated
     */
    public Integer getCthaschild() {
        return cthaschild;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_city.CTHASCHILD
     *
     * @param cthaschild the value for sys_city.CTHASCHILD
     *
     * @mbggenerated
     */
    public void setCthaschild(Integer cthaschild) {
        this.cthaschild = cthaschild;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_city.CTCOMMENT
     *
     * @return the value of sys_city.CTCOMMENT
     *
     * @mbggenerated
     */
    public String getCtcomment() {
        return ctcomment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_city.CTCOMMENT
     *
     * @param ctcomment the value for sys_city.CTCOMMENT
     *
     * @mbggenerated
     */
    public void setCtcomment(String ctcomment) {
        this.ctcomment = ctcomment == null ? null : ctcomment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_city.CTVALUE1
     *
     * @return the value of sys_city.CTVALUE1
     *
     * @mbggenerated
     */
    public String getCtvalue1() {
        return ctvalue1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_city.CTVALUE1
     *
     * @param ctvalue1 the value for sys_city.CTVALUE1
     *
     * @mbggenerated
     */
    public void setCtvalue1(String ctvalue1) {
        this.ctvalue1 = ctvalue1 == null ? null : ctvalue1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_city.CTVALUE2
     *
     * @return the value of sys_city.CTVALUE2
     *
     * @mbggenerated
     */
    public String getCtvalue2() {
        return ctvalue2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_city.CTVALUE2
     *
     * @param ctvalue2 the value for sys_city.CTVALUE2
     *
     * @mbggenerated
     */
    public void setCtvalue2(String ctvalue2) {
        this.ctvalue2 = ctvalue2 == null ? null : ctvalue2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_city.CTVALUE3
     *
     * @return the value of sys_city.CTVALUE3
     *
     * @mbggenerated
     */
    public String getCtvalue3() {
        return ctvalue3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_city.CTVALUE3
     *
     * @param ctvalue3 the value for sys_city.CTVALUE3
     *
     * @mbggenerated
     */
    public void setCtvalue3(String ctvalue3) {
        this.ctvalue3 = ctvalue3 == null ? null : ctvalue3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_city.CTVALUE4
     *
     * @return the value of sys_city.CTVALUE4
     *
     * @mbggenerated
     */
    public String getCtvalue4() {
        return ctvalue4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_city.CTVALUE4
     *
     * @param ctvalue4 the value for sys_city.CTVALUE4
     *
     * @mbggenerated
     */
    public void setCtvalue4(String ctvalue4) {
        this.ctvalue4 = ctvalue4 == null ? null : ctvalue4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_city.CTPARENT
     *
     * @return the value of sys_city.CTPARENT
     *
     * @mbggenerated
     */
    public Integer getCtparent() {
        return ctparent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_city.CTPARENT
     *
     * @param ctparent the value for sys_city.CTPARENT
     *
     * @mbggenerated
     */
    public void setCtparent(Integer ctparent) {
        this.ctparent = ctparent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_city.DELETED
     *
     * @return the value of sys_city.DELETED
     *
     * @mbggenerated
     */
    public Byte getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_city.DELETED
     *
     * @param deleted the value for sys_city.DELETED
     *
     * @mbggenerated
     */
    public void setDeleted(Byte deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_city.CREATED_BY
     *
     * @return the value of sys_city.CREATED_BY
     *
     * @mbggenerated
     */
    public Integer getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_city.CREATED_BY
     *
     * @param createdBy the value for sys_city.CREATED_BY
     *
     * @mbggenerated
     */
    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_city.CREATED_TIME
     *
     * @return the value of sys_city.CREATED_TIME
     *
     * @mbggenerated
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_city.CREATED_TIME
     *
     * @param createdTime the value for sys_city.CREATED_TIME
     *
     * @mbggenerated
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_city.UPDATED_BY
     *
     * @return the value of sys_city.UPDATED_BY
     *
     * @mbggenerated
     */
    public Integer getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_city.UPDATED_BY
     *
     * @param updatedBy the value for sys_city.UPDATED_BY
     *
     * @mbggenerated
     */
    public void setUpdatedBy(Integer updatedBy) {
        this.updatedBy = updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_city.UPDATED_TIME
     *
     * @return the value of sys_city.UPDATED_TIME
     *
     * @mbggenerated
     */
    public Date getUpdatedTime() {
        return updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_city.UPDATED_TIME
     *
     * @param updatedTime the value for sys_city.UPDATED_TIME
     *
     * @mbggenerated
     */
    public void setUpdatedTime(Date updatedTime) {
        this.updatedTime = updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_city.VERSION
     *
     * @return the value of sys_city.VERSION
     *
     * @mbggenerated
     */
    public Short getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_city.VERSION
     *
     * @param version the value for sys_city.VERSION
     *
     * @mbggenerated
     */
    public void setVersion(Short version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_city
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", ctid=").append(ctid);
        sb.append(", code=").append(code);
        sb.append(", ctcode=").append(ctcode);
        sb.append(", ctvalue=").append(ctvalue);
        sb.append(", ctorder=").append(ctorder);
        sb.append(", cthaschild=").append(cthaschild);
        sb.append(", ctcomment=").append(ctcomment);
        sb.append(", ctvalue1=").append(ctvalue1);
        sb.append(", ctvalue2=").append(ctvalue2);
        sb.append(", ctvalue3=").append(ctvalue3);
        sb.append(", ctvalue4=").append(ctvalue4);
        sb.append(", ctparent=").append(ctparent);
        sb.append(", deleted=").append(deleted);
        sb.append(", createdBy=").append(createdBy);
        sb.append(", createdTime=").append(createdTime);
        sb.append(", updatedBy=").append(updatedBy);
        sb.append(", updatedTime=").append(updatedTime);
        sb.append(", version=").append(version);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}